# Generated by Django 6.0.4 on 2026-04-16 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_author_photo_alter_book_cover_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40, unique=True)),
                ('phone', models.CharField(max_length=13, unique=True)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
